### ISSUE TITLE
Would you give me some tips?

### ISSUE THREAD

**Issue by TylerGe** [kayson/killitwithfire#1]
There are too many confuse dependencies between files. 
Could you give me some guides about this project?

**Comment by andva** [comment]
This is a five year old school project we were working on. The code is quite confusing and not that good for reference material. We based it on a paper called Physically based modeling and animation of fire by Duc Quang Nguyen, Ronald Fedkiw and Henrik Wann Jensen. I would suggest that you read that paper first. From there you should probably be able to map things together.

**Comment by TylerGe** [comment]
Thx. This paper helps me a lot.
