### ISSUE TITLE
Could u please tell me how to run this code? It seems struggling for MacOS.

### ISSUE THREAD

**Issue by Maikouuu** [kayson/killitwithfire#2]
Shown in tittle. Thanks.

**Comment by Maikouuu** [comment]
@kayson @andva @axelkinner @jojon5 @johanbecknoren Thanks sincerely!

**Comment by andva** [comment]
Mostly it was being developed on Windows. I looked into how easy it would be to run it but it wasn't that easy. As was mentioned by someone else in the other issue, the code is really messy and I don't think anyone of us has any time to make it compile again.

**Comment by Maikouuu** [comment]
Thanks man, ur code really inspired me a lot. Besides, I finally found that the main problem is some grammar error maybe due to different system and version of cmake, which troubles me a lot. If u want to fix it, my experience might help. Thanks.
